import { notFound, redirect } from "next/navigation";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { Container } from "@/components/ui/container";
import { PrintButton } from "@/components/deals/print-button";
import { OfferTermsSummary } from "@/components/offers/offer-terms-summary";
import { formatDate } from "@/lib/utils";

interface IpAssignmentPageProps {
  params: Promise<{ dealId: string }>;
}

export default async function IpAssignmentPage({ params }: IpAssignmentPageProps) {
  const { dealId } = await params;
  const session = await auth();
  if (!session?.user) redirect(`/auth/signin?callbackUrl=/deals/${dealId}/ip-assignment`);

  const deal = await prisma.deal.findUnique({
    where: { id: dealId },
    include: { listing: true, seller: true, buyer: true },
  });
  if (!deal) notFound();
  if (!deal.ipAssignmentGeneratedAt) notFound();

  const isParty = session.user.id === deal.sellerId || session.user.id === deal.buyerId;
  if (!isParty && session.user.role !== "ADMIN") notFound();

  return (
    <Container className="max-w-2xl py-10">
      <div className="mb-6 flex items-center justify-between print:hidden">
        <p className="rounded-lg border border-warning-500/30 bg-warning-50 px-3.5 py-2.5 text-xs text-warning-700">
          Simulated document for this prototype — not generated by a legal vendor and not
          legally binding.
        </p>
        <PrintButton />
      </div>

      <article className="rounded-xl border border-border bg-white p-8 text-sm leading-relaxed text-ink-800">
        <h1 className="text-center text-lg font-semibold text-ink-900">
          Intellectual Property Assignment Agreement
        </h1>
        <p className="mt-1 text-center text-xs text-ink-400">
          Generated {formatDate(deal.ipAssignmentGeneratedAt)} · Deal reference {deal.id}
        </p>

        <div className="mt-6 grid grid-cols-2 gap-6">
          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-ink-400">Assignor (Seller)</p>
            <p className="mt-1 font-medium text-ink-900">{deal.seller.name ?? deal.seller.email}</p>
            {deal.seller.company && <p className="text-ink-500">{deal.seller.company}</p>}
          </div>
          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-ink-400">Assignee (Buyer)</p>
            <p className="mt-1 font-medium text-ink-900">{deal.buyer.name ?? deal.buyer.email}</p>
            {deal.buyer.company && <p className="text-ink-500">{deal.buyer.company}</p>}
          </div>
        </div>

        <hr className="my-6 border-border" />

        <p>
          This Agreement confirms the transfer of all right, title, and interest in and to the
          concept, materials, and associated intellectual property described as{" "}
          <strong>&ldquo;{deal.listing.title}&rdquo;</strong> (the &ldquo;IP&rdquo;), from the
          Assignor to the Assignee, effective as of the date both parties confirm this Agreement
          within the Idea Exchange platform.
        </p>

        <div className="mt-4">
          <p className="text-xs font-semibold uppercase tracking-wide text-ink-400">Consideration</p>
          <div className="mt-1">
            <OfferTermsSummary
              amount={deal.finalAmount}
              equityPercent={deal.finalEquityPercent}
              royaltyPercent={deal.finalRoyaltyPercent}
              royaltyTermMonths={null}
            />
          </div>
        </div>

        <p className="mt-4">
          The Assignor represents that they are the sole owner of the IP and have full authority
          to assign it. The Assignee accepts the IP &ldquo;as-is&rdquo; on the basis of the
          diligence materials made available under the platform&apos;s NDA prior to this
          Agreement.
        </p>

        <div className="mt-8 grid grid-cols-2 gap-6 border-t border-border pt-6">
          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-ink-400">Assignor signature</p>
            <p className="mt-6 border-b border-ink-300 pb-1 text-ink-800">
              {deal.ipAssignmentSignedAt ? deal.seller.name ?? deal.seller.email : "Pending confirmation"}
            </p>
          </div>
          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-ink-400">Assignee signature</p>
            <p className="mt-6 border-b border-ink-300 pb-1 text-ink-800">
              {deal.ipAssignmentSignedAt ? deal.buyer.name ?? deal.buyer.email : "Pending confirmation"}
            </p>
          </div>
        </div>
        {deal.ipAssignmentSignedAt && (
          <p className="mt-2 text-xs text-ink-400">
            Confirmed by both parties on {formatDate(deal.ipAssignmentSignedAt)}.
          </p>
        )}
      </article>
    </Container>
  );
}
